import HeaderComponent from './header/HeaderComponent';
import CardCompnent from './card/CardComponent';
import FormComponent from './form/FormComponnet';
import CardResposComponent from './cardrespos/CardResposComponent';
import DetailComponent from './detail/DetailComponent';
import LoadingComponent from './loading/LoadingComponent';
import OptionComponent from './options/OptionComponent';
import TableComponent from './table/TableComponent';
import FormGroupComponent from './formgroup/FormGroupComponent';
import ActiveComponent from './actives/ActiveComponent';
import DailyComponent from './daily/DailyComponent';
export { DailyComponent, ActiveComponent, FormGroupComponent, TableComponent, OptionComponent, HeaderComponent, CardCompnent, FormComponent, CardResposComponent, DetailComponent, LoadingComponent };