import BannerComponent from './banner/BannerComponent';
import AboutComponent from './about/AboutComponent';
import ServiceComponent from './service/ServiceComponent';
import KingComponent from './king/KingComponent';
import TestimonialsComponent from './testimonials/TestimonialsComponent';
import FeatureComponent from './feature/FeatureComponent';
import BlogComponent from './blog/BlogComponent';
import ContactComponent from './contact/ContactComponent';
import SliderDetailComponent from './sliderdetail/SliderDetailComponent';
import RecentComponent from './recent/RecentComponent';
import BlogItemComponent from './blog/item/BlogItemComponent'
import TagComponent from './tags/TagComponent';
import InstagramComponent from './instagram/InstagramComponent'
import TourItem from './tour/TourItem';
import FormItem from './tour/FormItem';
import HeroComponent from './hero/HeroComponent';
import ToggleBoxComponent from './toggleBox/ToggleBoxComponent';
import BookComponent from './book/BookComponent';
import InfoComponent from './info/InfoComponent';
import ConfirmComponent from './confirm/ConfirmComponent';
import FormComment from './formcomment/FormComment';
import CommentItemComponent from './commentItem/CommentItemComponent';
import ProfileComponent from './profile/ProfileComponent';
export { ProfileComponent, CommentItemComponent, FormComment, ConfirmComponent, InfoComponent, BookComponent, ToggleBoxComponent, HeroComponent, FormItem, TourItem, InstagramComponent, TagComponent, BlogItemComponent, RecentComponent, SliderDetailComponent, ContactComponent, BlogComponent, BannerComponent, AboutComponent, ServiceComponent, KingComponent, TestimonialsComponent, FeatureComponent };